---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention 
summary: NetApp SnapMirror は、 LAN または WAN 経由でデータを高速でレプリケートするため、仮想環境と従来の環境の両方で、高いデータ可用性と高速なデータレプリケーションを実現できます。ネットアップストレージシステムにデータをレプリケートし、セカンダリデータを継続的に更新することで、データを最新の状態に保ちながら、必要なときにいつでもデータを利用できるようになります。外部レプリケーションサーバは必要ありません。 
---
= レプリケーションサービスについて説明します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror は、 LAN または WAN 経由でデータを高速でレプリケートするため、仮想環境と従来の環境の両方で、高いデータ可用性と高速なデータレプリケーションを実現できます。ネットアップストレージシステムにデータをレプリケートし、セカンダリデータを継続的に更新することで、データを最新の状態に保ちながら、必要なときにいつでもデータを利用できるようになります。外部レプリケーションサーバは必要ありません。



== の機能

* ONTAP ストレージシステム間でデータをレプリケートして、クラウドまたはクラウド間でバックアップとディザスタリカバリをサポートします。
* 高い可用性を備えた信頼性の高い DR 環境を実現します。
* ONTAP ストレージ間の効率的なブロックレベルのレプリケーションは高速かつ効率的で、 DR とバックアップの両方をきめ細かくリカバリできます。




== コスト

ネットアップでは、レプリケーションサービスの使用料は発生しませんが、データの入力と出力に該当する料金がクラウドプロバイダにあるかどうかを確認する必要があります。



== サポートされている作業環境

BlueXPを使用すると'次のような作業環境間でデータのレプリケーションを実行できます

[cols="30,30"]
|===
| ソースの作業環境 | サポートされるターゲットの作業環境 


| Cloud Volumes ONTAP  a| 
* ONTAP 対応の Amazon FSX
* Cloud Volumes ONTAP
* オンプレミスの ONTAP クラスタ




| オンプレミスの ONTAP クラスタ  a| 
* ONTAP 対応の Amazon FSX
* Cloud Volumes ONTAP
* オンプレミスの ONTAP クラスタ




| ONTAP 対応の Amazon FSX  a| 
* ONTAP 対応の Amazon FSX
* Cloud Volumes ONTAP
* オンプレミスの ONTAP クラスタ


|===


== データレプリケーションの仕組み

BlueXPは、SnapMirrorとSnapVault テクノロジを使用して、別々のONTAP システム上のボリューム間のデータレプリケーションを簡素化します。ソースボリュームとデスティネーションボリュームを特定し、レプリケーションポリシーとスケジュールを選択するだけで済みます。

Cloud Volumes ONTAP では、必要なディスクを購入し、関係を設定してレプリケーションポリシーを適用し、ボリューム間のベースライン転送を開始します。


NOTE: ベースライン転送には、ソースデータのフルコピーが含まれます。その後の転送には、ソースデータの差分コピーが含まれます。



== サポートされるデータ保護構成

BlueXPは、シンプル、ファンアウト、およびカスケードのデータ保護構成をサポートしています。

* シンプルな構成では、ボリューム A からボリューム B へのレプリケーションが行われます
* ファンアウト構成では、ボリューム A から複数のデスティネーションへのレプリケーションが行われます。
* カスケード構成では、レプリケーションはボリューム A からボリューム B 、およびボリューム B からボリューム C に行われます




== BlueXPのバックアップとリカバリを使用してデータをレプリケート

BlueXP Connector 3.9.31リリース以降では、BlueXPのバックアップとリカバリで、SnapMirrorテクノロジとSnapVaultテクノロジを使用して、別 々 のONTAPシステム上のボリューム間でデータをレプリケートできます。そのため、データを他のONTAPシステムにレプリケートし、同じデータのバックアップをオブジェクトストレージに作成する場合は、を使用することを推奨します https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["BlueXPのバックアップとリカバリ"^] データ保護のニーズを単一のサービスで管理できるようになります。

現在、次の機能はBlueXPレプリケーションサービスでのみサポートされます。BlueXPのバックアップとリカバリのレプリケーション機能を使用している場合はサポートされません。

* ボリュームAからボリュームBへ、さらにボリュームBからボリュームCへレプリケーションを行うカスケード構成はサポートされていません
* FSx for ONTAPシステムとの間でのデータのレプリケートはサポートされていません。
* ボリュームの1回限りのレプリケーションを作成することはできません。


そのため、この機能が必要な場合はBlueXPレプリケーションを使用してください。
